---
# this should go in repo root if kept, but I think it will be replaced by a prettier config.
extends: default

ignore: |
  node_modules/
  **/node_modules/

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
