#!/usr/bin/env bash
# env-file.sh — Shared env file writer for the github-app plugin
#
# Provides write_runtime_env_file() which generates the runtime env file
# that is sourced via CLAUDE_ENV_FILE. Both github-token-init.sh (initial
# write) and token-check.sh (token refresh writes) call this function so
# the two files never drift out of sync.
#
# Required variables when called:
#   ENV_RUNTIME_FILE   — path to the runtime env file to write
#   TOKEN_FILE         — path to the token file
#
# Optional variables (sourced from environment):
#   GITHUB_APP_ID
#   GITHUB_APP_PRIVATE_KEY_PATH
#   GITHUB_INSTALLATION_ID
#   GITHUB_APP_CLIENT_ID
#   GITHUB_APP_CLIENT_SECRET
#   GH_CONFIG_DIR
#   GIT_AUTHOR_NAME
#   GIT_AUTHOR_EMAIL
#   GIT_COMMITTER_NAME
#   GIT_COMMITTER_EMAIL

if [ "${_ENV_FILE_LOADED:-}" = "true" ]; then return 0; fi
_ENV_FILE_LOADED="true"

# Source agent-paths for AGENT_CONFIG_DIR
_env_file_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=agent-paths.sh
[[ "${_AGENT_PATHS_LOADED:-}" == "true" ]] || source "$_env_file_dir/agent-paths.sh"

# _safe_val VALUE
#
# Escapes a value for safe embedding in a double-quoted shell assignment.
# Handles $, `, \, ", and newlines so that sourcing the resulting file
# cannot cause shell injection.
_safe_val() {
  local v="$1"
  # Replace backslash first to avoid double-escaping
  v="${v//\\/\\\\}"
  v="${v//\$/\\\$}"
  v="${v//\`/\\\`}"
  v="${v//\"/\\\"}"
  printf '%s' "$v"
}

# write_runtime_env_file TOKEN
#
# Writes the full runtime env file with token vars + credential pointers
# + git identity vars. All git identity vars default to empty if unset,
# which preserves them across token refreshes when they are already
# exported in the current process.
#
# Values are escaped with _safe_val() so that special characters in git
# config values, tokens, or paths cannot cause shell injection when the
# file is sourced.
#
# Args:
#   $1  — the raw token string
write_runtime_env_file() {
  local token="$1"
  mkdir -p "$(dirname "$ENV_RUNTIME_FILE")"

  # Use a quoted heredoc for the static header, then append variable lines
  # with explicit escaping via _safe_val.
  cat > "$ENV_RUNTIME_FILE" <<'ENVEOF'
# Auto-generated by github-app plugin — do not edit manually.
# This file is rewritten on every token refresh. Add nothing else here.
ENVEOF

  # Write each export using _safe_val to prevent injection
  {
    printf 'export GH_TOKEN="%s"\n' "$(_safe_val "$token")"
    printf 'export GITHUB_TOKEN="%s"\n' "$(_safe_val "$token")"
    printf 'export GITHUB_TOKEN_FILE="%s"\n' "$(_safe_val "$TOKEN_FILE")"
    printf 'export GITHUB_APP_ENV_FILE="%s"\n' "$(_safe_val "$ENV_RUNTIME_FILE")"
    printf 'export GITHUB_APP_ID="%s"\n' "$(_safe_val "${GITHUB_APP_ID:-}")"
    printf 'export GITHUB_APP_PRIVATE_KEY_PATH="%s"\n' "$(_safe_val "${GITHUB_APP_PRIVATE_KEY_PATH:-}")"
    printf 'export GITHUB_INSTALLATION_ID="%s"\n' "$(_safe_val "${GITHUB_INSTALLATION_ID:-}")"
    printf 'export GIT_AUTHOR_NAME="%s"\n' "$(_safe_val "${GIT_AUTHOR_NAME:-}")"
    printf 'export GIT_AUTHOR_EMAIL="%s"\n' "$(_safe_val "${GIT_AUTHOR_EMAIL:-}")"
    printf 'export GIT_COMMITTER_NAME="%s"\n' "$(_safe_val "${GIT_COMMITTER_NAME:-}")"
    printf 'export GIT_COMMITTER_EMAIL="%s"\n' "$(_safe_val "${GIT_COMMITTER_EMAIL:-}")"
    echo "# Note: the identity defaults above preserve identity across token refreshes"
    echo "# only because CLAUDE_ENV_FILE is sourced before PreToolUse runs, so the vars"
    echo "# are already exported in the caller's environment. If token-check.sh is ever"
    echo "# run in a context that doesn't source CLAUDE_ENV_FILE first, these vars would"
    echo "# be written as empty strings and identity would be lost."
  } >> "$ENV_RUNTIME_FILE"

  [[ -n "${GITHUB_APP_CLIENT_ID:-}" ]] && printf 'export GITHUB_APP_CLIENT_ID="%s"\n' "$(_safe_val "$GITHUB_APP_CLIENT_ID")" >> "$ENV_RUNTIME_FILE"
  [[ -n "${GITHUB_APP_CLIENT_SECRET:-}" ]] && printf 'export GITHUB_APP_CLIENT_SECRET="%s"\n' "$(_safe_val "$GITHUB_APP_CLIENT_SECRET")" >> "$ENV_RUNTIME_FILE"
  # Preserve GH_CONFIG_DIR isolation across token refreshes
  [[ -n "${GH_CONFIG_DIR:-}" ]] && printf 'export GH_CONFIG_DIR="%s"\n' "$(_safe_val "$GH_CONFIG_DIR")" >> "$ENV_RUNTIME_FILE"
  chmod 600 "$ENV_RUNTIME_FILE"
}

# GIT_IDENTITY_FILE — path to the stable git identity file
# Written once at session start; never overwritten by token refresh.
# Uses AGENT_CONFIG_DIR (per-agent) so multiple agents on the same machine
# don't stomp on each other's identity file. Falls back to a HOME-scoped
# path if AGENT_CONFIG_DIR is not yet set (should not happen in normal usage).
GIT_IDENTITY_FILE="${AGENT_CONFIG_DIR:-${HOME}/.agents/_UNKNOWN/.config}/github-git-identity"

# write_git_identity_file BOT_NAME BOT_EMAIL
#
# Writes a stable file containing only the git identity env vars.
# This file is NOT overwritten by token-check.sh, so identity survives
# even if the env file template drifts or is changed in the future.
#
# The file is sourced from CLAUDE_ENV_FILE after the runtime env file,
# so it takes precedence if the runtime env file somehow drops these vars.
#
# Values are escaped with _safe_val() to prevent shell injection from
# git config values containing special characters.
#
# Args:
#   $1  — bot name  (e.g. "my-app[bot]")
#   $2  — bot email (e.g. "12345+my-app[bot]@users.noreply.github.com")
write_git_identity_file() {
  local bot_name="$1"
  local bot_email="$2"
  mkdir -p "$(dirname "$GIT_IDENTITY_FILE")"

  cat > "$GIT_IDENTITY_FILE" <<'GITEOF'
# Stable git identity for GitHub App bot — written by github-app plugin at session start
# This file is NOT overwritten by token refreshes. Delete it to force a refresh.
GITEOF

  {
    printf 'export GIT_AUTHOR_NAME="%s"\n' "$(_safe_val "$bot_name")"
    printf 'export GIT_AUTHOR_EMAIL="%s"\n' "$(_safe_val "$bot_email")"
    printf 'export GIT_COMMITTER_NAME="%s"\n' "$(_safe_val "$bot_name")"
    printf 'export GIT_COMMITTER_EMAIL="%s"\n' "$(_safe_val "$bot_email")"
  } >> "$GIT_IDENTITY_FILE"

  chmod 600 "$GIT_IDENTITY_FILE"
}

# GIT_CREDENTIAL_HELPER_FILE — stable path for the per-agent credential helper script.
# Written once at session start by write_stable_credential_helper().
# Lives under AGENT_CONFIG_DIR so it never includes a plugin version number,
# meaning it remains valid across plugin upgrades (BUG-12 fix).
GIT_CREDENTIAL_HELPER_FILE="${AGENT_CONFIG_DIR:-${HOME}/.agents/_UNKNOWN/.config}/git-credential-helper.sh"

# write_stable_credential_helper TOKEN_FILE_PATH
#
# Writes a small bash credential helper script to a stable, non-versioned
# path under AGENT_CONFIG_DIR. The script reads the GitHub App installation
# token from TOKEN_FILE and outputs git credential protocol lines.
#
# Unlike pointing gitconfig at ${CLAUDE_PLUGIN_ROOT}/bin/git-credential-github-app.sh
# (which embeds the plugin version in the path and becomes stale when the
# plugin is updated), this file lives at a path that never changes. It is
# rewritten on every session start so its contents stay current, but the
# path recorded in GIT_CONFIG_GLOBAL never needs updating. (BUG-12 fix)
#
# Args:
#   $1  — path to the token file (GITHUB_TOKEN_FILE)
write_stable_credential_helper() {
  local token_file="${1:-${TOKEN_FILE:-}}"
  local target="${GIT_CREDENTIAL_HELPER_FILE}"
  mkdir -p "$(dirname "$target")"

  cat > "$target" <<HELPEREOF
#!/usr/bin/env bash
# Auto-generated by github-app plugin — do not edit manually.
# Reads the GitHub App installation token from the token file and returns
# it as git credentials. Rewritten on every session start by github-token-init.sh.
TOKEN_FILE="${token_file}"
case "\${1:-}" in
  get)
    if [[ -f "\$TOKEN_FILE" ]]; then
      TOKEN=\$(cat "\$TOKEN_FILE")
      if [[ -n "\$TOKEN" ]]; then
        printf 'protocol=https\nhost=github.com\nusername=x-access-token\npassword=%s\n' "\$TOKEN"
      fi
    fi
    ;;
  store|erase) ;;  # no-op: token lifecycle is managed by plugin hooks
esac
HELPEREOF

  chmod 700 "$target"
}

# write_git_config_global [CREDENTIAL_HELPER_PATH]
#
# Rewrites the isolated gitconfig with current identity from env vars
# (GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL) plus the credential helper.
# Git reads GIT_CONFIG_GLOBAL on every operation, so changes take
# effect immediately on the next git command.
#
# The target path is computed at call-time (not source-time) so the
# function always uses the current value of GIT_CONFIG_GLOBAL, avoiding
# order-dependent bugs when callers source this lib at different points.
#
# Args:
#   $1  — (optional) path to credential helper script. If omitted,
#         reuses the existing [credential] section or omits it.
write_git_config_global() {
  local cred_helper="${1:-}"
  local bot_name="${GIT_AUTHOR_NAME:-}"
  local bot_email="${GIT_AUTHOR_EMAIL:-}"
  local target="${GIT_CONFIG_GLOBAL:-${AGENT_CONFIG_DIR:-${HOME}/.agents/_UNKNOWN/.config}/git/config}"

  [[ -n "$bot_name" && -n "$bot_email" ]] || return 0

  mkdir -p "$(dirname "$target")"

  cat > "$target" <<GCEOF
[user]
    name = ${bot_name}
    email = ${bot_email}
GCEOF

  if [[ -n "$cred_helper" ]]; then
    cat >> "$target" <<GCEOF
[credential "https://github.com"]
    helper = !${cred_helper}
GCEOF
  fi

  chmod 600 "$target"
}
