#!/usr/bin/env bash
# env-file.sh — Shared env file writer for the github-app plugin
#
# Provides write_runtime_env_file() which generates the runtime env file
# that is sourced via CLAUDE_ENV_FILE. Both github-token-init.sh (initial
# write) and token-check.sh (token refresh writes) call this function so
# the two files never drift out of sync.
#
# Required variables when called:
#   ENV_RUNTIME_FILE   — path to the runtime env file to write
#   TOKEN_FILE         — path to the token file
#
# Optional variables (sourced from environment):
#   GITHUB_APP_ID
#   GITHUB_APP_PRIVATE_KEY_PATH
#   GITHUB_INSTALLATION_ID
#   GITHUB_APP_CLIENT_ID
#   GITHUB_APP_CLIENT_SECRET
#   GH_CONFIG_DIR
#   GIT_AUTHOR_NAME
#   GIT_AUTHOR_EMAIL
#   GIT_COMMITTER_NAME
#   GIT_COMMITTER_EMAIL

if [ "${_ENV_FILE_LOADED:-}" = "true" ]; then return 0; fi
_ENV_FILE_LOADED="true"

# write_runtime_env_file TOKEN
#
# Writes the full runtime env file with token vars + credential pointers
# + git identity vars. All git identity vars default to empty if unset,
# which preserves them across token refreshes when they are already
# exported in the current process.
#
# Args:
#   $1  — the raw token string
write_runtime_env_file() {
  local token="$1"
  mkdir -p "$(dirname "$ENV_RUNTIME_FILE")"
  cat > "$ENV_RUNTIME_FILE" <<ENVEOF
# Auto-generated by github-app plugin — do not edit manually.
# This file is rewritten on every token refresh. Add nothing else here.
export GH_TOKEN="$token"
export GITHUB_TOKEN="$token"
export GITHUB_TOKEN_FILE="$TOKEN_FILE"
export GITHUB_APP_ENV_FILE="$ENV_RUNTIME_FILE"
export GITHUB_APP_ID="${GITHUB_APP_ID:-}"
export GITHUB_APP_PRIVATE_KEY_PATH="${GITHUB_APP_PRIVATE_KEY_PATH:-}"
export GITHUB_INSTALLATION_ID="${GITHUB_INSTALLATION_ID:-}"
export GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME:-}"
export GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL:-}"
export GIT_COMMITTER_NAME="${GIT_COMMITTER_NAME:-}"
export GIT_COMMITTER_EMAIL="${GIT_COMMITTER_EMAIL:-}"
# Note: the ${GIT_*:-} defaults above preserve identity across token refreshes
# only because CLAUDE_ENV_FILE is sourced before PreToolUse runs, so the vars
# are already exported in the caller's environment. If token-check.sh is ever
# run in a context that doesn't source CLAUDE_ENV_FILE first, these vars would
# be written as empty strings and identity would be lost.
ENVEOF
  [[ -n "${GITHUB_APP_CLIENT_ID:-}" ]] && echo "export GITHUB_APP_CLIENT_ID=\"$GITHUB_APP_CLIENT_ID\"" >> "$ENV_RUNTIME_FILE"
  [[ -n "${GITHUB_APP_CLIENT_SECRET:-}" ]] && echo "export GITHUB_APP_CLIENT_SECRET=\"$GITHUB_APP_CLIENT_SECRET\"" >> "$ENV_RUNTIME_FILE"
  # Preserve GH_CONFIG_DIR isolation across token refreshes
  [[ -n "${GH_CONFIG_DIR:-}" ]] && echo "export GH_CONFIG_DIR=\"$GH_CONFIG_DIR\"" >> "$ENV_RUNTIME_FILE"
  chmod 600 "$ENV_RUNTIME_FILE"
}

# GIT_IDENTITY_FILE — path to the stable git identity file
# Written once at session start; never overwritten by token refresh.
# Uses AGENT_CONFIG_DIR (per-agent) so multiple agents on the same machine
# don't stomp on each other's identity file. Falls back to a HOME-scoped
# path if AGENT_CONFIG_DIR is not yet set (should not happen in normal usage).
GIT_IDENTITY_FILE="${AGENT_CONFIG_DIR:-${HOME}/.agents/_UNKNOWN/.config}/github-git-identity"

# write_git_identity_file BOT_NAME BOT_EMAIL
#
# Writes a stable file containing only the git identity env vars.
# This file is NOT overwritten by token-check.sh, so identity survives
# even if the env file template drifts or is changed in the future.
#
# The file is sourced from CLAUDE_ENV_FILE after the runtime env file,
# so it takes precedence if the runtime env file somehow drops these vars.
#
# Args:
#   $1  — bot name  (e.g. "my-app[bot]")
#   $2  — bot email (e.g. "12345+my-app[bot]@users.noreply.github.com")
write_git_identity_file() {
  local bot_name="$1"
  local bot_email="$2"
  mkdir -p "$(dirname "$GIT_IDENTITY_FILE")"
  cat > "$GIT_IDENTITY_FILE" <<GITEOF
# Stable git identity for GitHub App bot — written by github-app plugin at session start
# This file is NOT overwritten by token refreshes. Delete it to force a refresh.
export GIT_AUTHOR_NAME="$bot_name"
export GIT_AUTHOR_EMAIL="$bot_email"
export GIT_COMMITTER_NAME="$bot_name"
export GIT_COMMITTER_EMAIL="$bot_email"
GITEOF
  chmod 600 "$GIT_IDENTITY_FILE"
}
